{
  "created": "2017-08-04T21:05:28.832Z",
  "description": "https://bugzil.la/1387553",
  "expandedScopes": [
    "assume:mozilla-user:cliu@mozilla.com",
    "assume:project:taskcluster:tutorial",
    "queue:create-task:aws-provisioner-v1/tutorial",
    "queue:create-task:low:built-in/*",
    "queue:route:index.garbage.*",
    "queue:route:notify.email.*",
    "queue:scheduler-id:tutorial",
    "secrets:get:garbage/*",
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-release.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-release.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-release.token",
    "secrets:set:garbage/*",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-release.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-release.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-release.token"
  ],
  "lastModified": "2017-08-04T21:05:28.832Z",
  "roleId": "mozilla-user:cliu@mozilla.com",
  "scopes": [
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-1/pocket-api-release.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-2/pocket-api-release.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-beta.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-nightly.token",
    "secrets:get:project/releng/gecko/build/level-3/pocket-api-release.token",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-1/pocket-api-release.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-2/pocket-api-release.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-beta.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-nightly.token",
    "secrets:set:project/releng/gecko/build/level-3/pocket-api-release.token"
  ]
}
